### ISSUE TITLE
ES6 import support

### ISSUE THREAD

**Issue by erasmo-marin** [tjmehta/keypather#22]
Hi, it would be great if import support is improved and documented.

Right now it's possible to use ES6 import with keypather this way, but it's not clean and you create a new instance every time you need it:
```
import { default as keypather } from 'keypather';

let myKeypather = keypather();
```

something like this would be better:

```
import keypather from 'keypather';
//if you need to set options
keypather.setOptions({...});
```

**Comment by tjmehta** [comment]
`keypather` actually exports a `class`. That can conveniently be used as a factory.

Feel free to do this if it is clearer for you:
```js
import { default as Keypather } from 'keypather';

let keypather = new Keypather();
```

Let me know if this sounds right, and have suggestions for doc updates.

**Comment by erasmo-marin** [comment]
Yeah, I think it's fine, it's basically the same what I was doing. And you are right, it's more flexible to use it as a factory instead of having a constant as I suggested in the first place.

I think it should be documented anyways. I'm going to make a PR if you are ok with it.

Thanks.
