### ISSUE TITLE
Library does not support Json Keys with characters '-'

### ISSUE THREAD

**Issue by harrysingh** [tjmehta/keypather#32]
I was trying to use the Library for parsing a folder structure having set of files and creating an object out of it.

I get error for a key which has hyphen in file name
`          if (!/^[A-Za-z0-9_$]$/.test(character)) throw new Error(parseErrorMessage(state, 'invalid dot key'))
                                                  ^
Error: Error parsing keypath 'how-to' at char 4 '-': invalid dot key
`

**Comment by tjmehta** [comment]
Hey @harrysingh let me know if you’re still having this issue. I believe it should be resolved. Sorry for the late reply
