### ISSUE TITLE
🚨 Potential Security Vulnerability - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [tjmehta/keypather#44]
#### ⚠️ Potential Vulnerability in keypather

👋 Hello, @tjmehta - @nav-prak has disclosed a potential vulnerability in your repository. To validate or invalidate this potential vulnerability, please visit https://huntr.dev/bounties/2-npm-keypather and join our community in helping secure open-source code.

---

#### ☎️ Need further support?

Come and join us on our [Discord](https://huntr.dev/discord) and a member of our team will be happy to help! 🤗

cc - @JamieSlome

**Comment by Aravindha1234u** [comment]
@tjmehta Can you review the PR, I have fixed it.

**Comment by tjmehta** [comment]
other people have reported this we do not consider prototype pollution a security issue for keypather. for example, lodash set is similar and does not handle prototype pollution. 

developers that use any user passed strings with set or file is the real security issue. this is not IMO.

happy to look at anything if you see something, thanks!
