### ISSUE TITLE
Error: Unexpected token '/' in keypath 'channels.smartylighting/streetlights/1/0/action/{streetlightId}/turn/on.publish.message.payload' at position 23 (invalid dot key)

### ISSUE THREAD

**Issue by KhudaDad414** [tjmehta/keypather#45]
I am trying to use this library but the limitation on characters that I can use makes it impossible to use for me.
I mean why it won't work if I have '/' or '{' in my keypath?
is it possible to give the developers an option to select their separator and then treat all other characters as normal characters?

**Comment by tjmehta** [comment]
keypather is meant to support syntactically correct javascript, but you are allowed to pass in your own `delimeter` as an option. can you provide some example code that helps trigger the error you’re hitting? I haven’t modified this code in over 2 years, so I’m not exactly sure what validation is triggering that error. thanks

**Comment by tjmehta** [comment]
hey @KhudaDad414 upon further inspection I realized a solution that will probably work for you:

```kp.get(`channels['smartylighting/streetlights/1/0/action/${streetlightId}/turn/on'].publish.message.payload`)```

as I mentioned above keypather assumes that the string passed in is syntactically correct js (it doesn't use eval under the hood, but think of it that way).

hope that helps

**Comment by KhudaDad414** [comment]
Thanks😊
