### ISSUE TITLE
Accept an array

### ISSUE THREAD

**Issue by tomekwi** [tjmehta/keypather#9]
Instead of `"a.b.c"` keypather could accept an array like `["a", "b", "c"]`. As [object-path](http://npm.im/object-path) does it.

Here's why.
- it coughs up on setting things like `{"[key]": "value"}`
- when you have:
```js
var keys = ["a", "[b]", "c()", "'d\''"];
```
…it seems very wrong to do:
```js
keypather.set(...
  , keys.map(function (key) {
    return "['" + key.replace(/\\/g, "\\\\").replace(/'/g, "\\'") + "']"
    }).join("")
  );
```

…when you could just:
```js
keypather.set(..., keys);
```

**Comment by tjmehta** [comment]
Interesting, where is the initial array coming from?

**Comment by tomekwi** [comment]
I don't remember exactly now. I think it was a data tree created by [dox](https://www.npmjs.org/package/dox) – I had to map it to another tree with many layers.

**Comment by tomekwi** [comment]
Generically speaking, recursion.

**Comment by tjmehta** [comment]
The reason why I ask is for the items "[b]" and "'d'".  If it weren't for this you'd be able to just keypath = arr.join('.')



—@tjmehta
Typed using my thumbs..

**Comment by tomekwi** [comment]
Oh, that's again the same thing :) We've been documenting a CSS framework with a hierarchical structure of classes. Some tags in the hierarchy (which became object keys) had funny characters like `[` and `'`.

**Comment by tjmehta** [comment]
I don't think I would be able to support "[b]" specifically bc keypather would actually think b is a key on the scope and use its value as the key in within the brackets. Just like vanilla JS, for a[b]  b is assumed as a var (keypather does the same it except it assumes vars are on the given object keypather.get({ a:{ c:1 }, b: 'c' }, a[b]) results in 1.



—@tjmehta
Typed using my thumbs..

**Comment by tomekwi** [comment]
How about assuming that all items are simply keys when passing an array?

That would allow to use keypather in generic situations – for example when we don't know the keys we'd have to process.

**Comment by tomekwi** [comment]
:bell: @justsml @tjmehta any thoughts on this?

At the moment it's unsafe to run `keypath.set(object, keys.join("."))` when we don't have 100% control over `keys`.

**Comment by tjmehta** [comment]
Can all the keys be assumed to be js syntax (ex:` ['foo', '[1]', '["foo"]']`) ?

**Comment by tomekwi** [comment]
Well, that's the same problem again.

Real-life scenario. We have a bunch of items, each of them has a "path", as in a filesystem. Like this:

```js
[ { path: ["a", "[b]", "'c'"]
  , value: 1
  }
, { path: ["a", "[b]"]
  , value: 2
  }
, { path: ["a", "[b]", "d()"]
  , value: 3
  }
]
```

We need to map them to a tree structure – creating branches when we need them. Say, like this:

```js
{ "a":
  { value: 1
  , children:
    { "b":
      { children:
        { "'c'": {value: 2}
        , "d()": {value: 3}
        }
      }
    }
  }
}
```

Seems a perfect fit for keypather – but at the moment it's not.

By the way, even as far as implementation is concerned – isn't it a lot easier to assume that `["a", "[b]", "d()"]` maps to `["a"]["[b]"]["d()"]` than to calculate `["a"][b][d()]`?

**Comment by tomekwi** [comment]
Hey this could also be another opt-in module as per #11.

```js
var get = require('keypather/get-from-array');
var set = require('keypather/set-from-array');

set(object, ["a", "[b]", "d()"]);
```

**Comment by tjmehta** [comment]
Another alternative is a join function.




`keypather.join(["a", "[b]", "d()”])`




That would avoid creating array versions of each of the methods


—
@tjmehta

**Comment by tomekwi** [comment]
Hmm, I see your point. Does that mean

```js
keypather.join(["a", "[b]", "d()”]) == "a['[b]']['d()']"

**Comment by tjmehta** [comment]
keypather.join(["a", "[b]", "d()”]) == "a[b].d()"



—
@tjmehta

**Comment by tomekwi** [comment]
But this means accessing `{a: {"[b]": {"d()": 1}}}` is difficult and slow. And that's the initial problem.

**Comment by tjmehta** [comment]
Hmm. I don't fully understand your problem. Maybe you can send me more details. How are you getting an array?



—@tjmehta
Typed using my thumbs..

**Comment by tjmehta** [comment]
Hmm, I understand now.

**Comment by tjmehta** [comment]
So you have an array of exact keys (which may look like keypaths).
```js
var val = ["a", "[b]", "d()"].reduce(function (obj, key) {
  return obj(key);
}, obj);
// maybe what you want is a 101/get
var get = require('101/get');*

var val = ["a", "[b]", "d()"].reduce(get, obj);
```
*[tjmehta/101](http://github.com/tjmehta/101)

Is that solution good enough or are you also wanting behavior like keypather that ignores accessing properties of `undefined`?

**Comment by tomekwi** [comment]
In my case I needed both to ignore accessing `undefined` properties, but also creating them if they don't exist through `keypather/set`.

But I guess it's not a question of one use-case. It's quite a generic wish – an option which is not as powerful and idiomatic, but more:
- lightweight – no need to analyze the strings
- robust – works for any set of keys (for example, from user input)

**Comment by tjmehta** [comment]
stale issue.
